# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
en:
  languageCode: en-us
  title: Kohei Shinden
  params:
    description: Kohei Shinden's portfolio website
  contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
ja:
  languageCode: ja
  contentDir: content/ja
  title: 新田洸平
  params:
    description: 新田洸平のポートフォリオサイト
#zh:
#  languageCode: zh-Hans
#  contentDir: content/zh
#  title: Chinese website title...
#  params:
#    description: Site description in Chinese...
#  menu:
#    main:
#      - name: 传
#        url: '#about'
#        weight: 1
